src/main/kotlin/com/sparta/tobiro/domain/member/model/Admin.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Member.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Owner.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Role.kt, src/main/kotlin/com/sparta/tobiro/domain/member/repository/MemberRepository.kt, src/main/kotlin/com/sparta/tobiro/domain/member/repository/OwnerRepository.kt
1. Member Entity 추가
2. Owner Entity 추가
3. Admin Entity 추가
4. Member Repository 추가
5. Owner Repository 추가
=> ✨Feat: 회원가입 Entity 기능 추가

src/main/kotlin/com/sparta/tobiro/domain/reservation/model/Reservation.kt, src/main/kotlin/com/sparta/tobiro/domain/reservation/repository/ReservationRepository.kt
1. reservation Entity 작성
2. reservation Repository 작성
=> ✨Feat: reservation entity, repository 작성

src/main/kotlin/com/sparta/tobiro/domain/accommodation/model/RoomInfo.kt, src/main/kotlin/com/sparta/tobiro/domain/accommodation/repository/RoomInfoRepository.kt
1. RoomInfo Entity 작성
2. RoomInfoRepository 작성
=> ✨Feat: 숙박업소 객실 정보 Entity 및 Repository 작성

src/main/kotlin/com/sparta/tobiro/TobiroApplication.kt, src/main/kotlin/com/sparta/tobiro/domain/accommodation/model/AccommodationInfo.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Admin.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Member.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Owner.kt, src/main/kotlin/com/sparta/tobiro/domain/reservation/model/Reservation.kt, src/main/kotlin/com/sparta/tobiro/global/entity/BaseTimeEntity.kt
1. AccommodationInfo Entity 수정
2. Admin Entity 수정
3. Member Entity 수정
4. Owner Entity 수정
5. Reservation Entity 수정
6. EnableJpaAuditing 설정
7. BaseTimeEntity 클래스 추가
=> ✨Feat: BaseEntity 추가 및 JpaAuditing 설정

src/main/kotlin/com/sparta/tobiro/api/member/controller/MemberController.kt, src/main/kotlin/com/sparta/tobiro/api/member/controller/OwnerController.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/MemberResponse.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/MemberSignUpRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/OwnerResponse.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/OwnerSignUpRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Member.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Owner.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Profile.kt, src/main/kotlin/com/sparta/tobiro/domain/member/repository/MemberRepository.kt, src/main/kotlin/com/sparta/tobiro/domain/member/repository/OwnerRepository.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/MemberService.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/MemberServiceImpl.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/OwnerService.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/OwnerServiceImpl.kt, src/main/kotlin/com/sparta/tobiro/infra/security/SecurityConfig.kt
1. Owner Entity작성
2. OwnerRepository 작성
3. OwnerController 작성
4. OwnerService 작성
5. OwnerServiceImpl 작성
6. OwnerResponse 작성
7. OwnerSignUpRequest 작성 
8 OwnerSecurityConfig 테스트를 위한 URL 수정
=> ✨Feat: Owner 회원가입기능 추가

src/main/kotlin/com/sparta/tobiro/api/accommodation/controller/BackOfficeController.kt, src/main/kotlin/com/sparta/tobiro/api/accommodation/dto/request/UpdateAccommodationRequest.kt, src/main/kotlin/com/sparta/tobiro/api/accommodation/dto/response/AccommodationResponse.kt, src/main/kotlin/com/sparta/tobiro/domain/accommodation/model/Accommodation.kt, src/main/kotlin/com/sparta/tobiro/domain/accommodation/model/Room.kt, src/main/kotlin/com/sparta/tobiro/domain/accommodation/repository/AccommodationInfoRepository.kt, src/main/kotlin/com/sparta/tobiro/domain/accommodation/repository/AccommodationRepository.kt, src/main/kotlin/com/sparta/tobiro/domain/accommodation/repository/RoomRepository.kt, src/main/kotlin/com/sparta/tobiro/domain/accommodation/service/AccommodationService.kt, src/main/kotlin/com/sparta/tobiro/domain/reservation/model/Reservation.kt, src/main/kotlin/com/sparta/tobiro/global/exception/GlobalExceptionHandler.kt, src/main/kotlin/com/sparta/tobiro/global/exception/ModelNotFoundException.kt, src/main/kotlin/com/sparta/tobiro/global/exception/dto/ErrorResponse.kt
1. AccommodationInfo Entity 이름 Accommodation으로 수정
2. RoomInfo Entity 이름 Room으로 수정
3. Controller, Service, Repository, dto 작성
4. 해당 숙박 데이터가 없을 경우 예외처리 - GlobalExceptionHandler 작성 - ErrorResponse dto 작성 - ModelNotFoundException 작성
5. Reservation Entity 수정 - RoomInfo -> Room
=> ✨Feat: 숙박 수정 기능 추가

src/main/kotlin/com/sparta/tobiro/api/accommodation/controller/BackOfficeController.kt, src/main/kotlin/com/sparta/tobiro/domain/accommodation/service/AccommodationService.kt
=> ✨Feat: 숙박업소 정보 조회 기능 추가

src/main/kotlin/com/sparta/tobiro/api/member/controller/MemberController.kt, src/main/kotlin/com/sparta/tobiro/api/member/controller/OwnerController.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/UpdateMemberProfileRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/UpdateOwnerProfileRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/MemberService.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/MemberServiceImpl.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/OwnerService.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/OwnerServiceImpl.kt, src/main/kotlin/com/sparta/tobiro/global/exception/RoleExceptionHandler.kt, src/main/kotlin/com/sparta/tobiro/global/exception/RoleNotFoundException.kt
1. Controller updateMemberProfile 작성
2. Service updateMemberProfile 작성
3. ServiceImpl updateMemberProfile 작성
4. Controller updateOwnerProfile 작성
5. Service updateOwnerProfile 작성
6. ServiceImpl updateOwnerProfile 작성
=> ✨Feat: Owner , Member 프로필수정기능 추가

src/main/kotlin/com/sparta/tobiro/api/member/controller/MemberController.kt, src/main/kotlin/com/sparta/tobiro/api/member/controller/OwnerController.kt, src/main/kotlin/com/sparta/tobiro/domain/member/repository/MemberRepository.kt, src/main/kotlin/com/sparta/tobiro/domain/member/repository/OwnerRepository.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/MemberService.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/MemberServiceImpl.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/OwnerService.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/OwnerServiceImpl.kt, src/main/kotlin/com/sparta/tobiro/global/exception/GlobalExceptionHandler.kt, src/main/kotlin/com/sparta/tobiro/infra/security/SecurityConfig.kt, src/main/kotlin/com/sparta/tobiro/infra/swagger/SwaggerConfig.kt, src/main/resources/application.yml
1.  Owner Controller login 구현 
2.  Owner Repository 예외체리 구현
3.  Owner ServiceImpl login 구현 
4.  Member Controller login 구현 
5.  Member Repository 예외체리 구현
6.  Member ServiceImpl login 구현 
7.  SecurityConfig 로그인뺴고 다 안되게 구현
8.  SwaggerConfig Available 구현
9.  RoleNotFoundException 를 GlobalExceptionHandler 로 옴겼음
10. application.yml 토큰 어플리케이션 구현
11. Jwt 토큰과 필터
=> ✨Feat: Owner , Member Login 기능 추가

src/main/kotlin/com/sparta/tobiro/api/member/controller/MemberController.kt, src/main/kotlin/com/sparta/tobiro/api/member/controller/OwnerController.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/LoginRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/MemberSignUpRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/OwnerSignUpRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/UpdateMemberProfileRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/UpdateOwnerProfileRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/response/LoginResponse.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/response/MemberResponse.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/response/OwnerResponse.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Member.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Owner.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/MemberService.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/MemberServiceImpl.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/OwnerService.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/OwnerServiceImpl.kt, src/main/kotlin/com/sparta/tobiro/global/exception/InvalidCredentialException.kt, src/main/kotlin/com/sparta/tobiro/infra/security/CustomAuthenticationEntryPoint.kt, src/main/kotlin/com/sparta/tobiro/infra/security/Memberprincpal.kt, src/main/kotlin/com/sparta/tobiro/infra/security/PasswordEncoderConfig.kt, src/main/kotlin/com/sparta/tobiro/infra/security/SecurityConfig.kt, src/main/kotlin/com/sparta/tobiro/infra/security/jwt/JwtAuthenticationFilter.kt, src/main/kotlin/com/sparta/tobiro/infra/security/jwt/JwtAuthenticationToken.kt, src/main/kotlin/com/sparta/tobiro/infra/security/jwt/JwtPlugin.kt
=> ✨Feat: 인가기능 추가 및 인증기능에서 빠진jwt 추가

src/main/kotlin/com/sparta/tobiro/api/member/controller/MemberController.kt, src/main/kotlin/com/sparta/tobiro/api/member/controller/OwnerController.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/OwnerSignUpRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/UpdateMemberProfileRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/UpdateOwnerProfileRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Owner.kt, src/main/kotlin/com/sparta/tobiro/domain/member/repository/OwnerRepository.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/MemberServiceImpl.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/OwnerServiceImpl.kt, src/main/kotlin/com/sparta/tobiro/infra/security/SecurityConfig.kt, src/main/kotlin/com/sparta/tobiro/infra/security/UserPrincipal.kt, src/main/kotlin/com/sparta/tobiro/infra/security/jwt/JwtAuthenticationFilter.kt, src/main/kotlin/com/sparta/tobiro/infra/security/jwt/JwtAuthenticationToken.kt
1. 필터에서 memberid,ownerid 저장로직구현
2. MemberServiceImpl에서 로그인한 사용자와 요청한 사용자 id 비교 로직
3. OwnerServiceImpl에서  로그인한 사용자와 요청한 사용자 id 비교 로직
=> ✨Feat: 프로필수정 인가 구현

src/main/kotlin/com/sparta/tobiro/infra/security/CustomAccessDeniedHandler.kt, src/main/kotlin/com/sparta/tobiro/infra/security/SecurityConfig.kt
1.  CustomAccessDeniedHandler 추가 구현
2.  CustomAccessDeniedHandler 를 SecurityConfig에 연결
=> ✨Feat: CustomAccessDeniedHandler 추가 구현하고 SecurityConfig에 연결

src/main/kotlin/com/sparta/tobiro/api/member/controller/MemberController.kt, src/main/kotlin/com/sparta/tobiro/api/member/controller/OwnerController.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/MemberSignUpRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/OwnerSignUpRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/validation/ValidName.kt, src/main/kotlin/com/sparta/tobiro/domain/member/validation/ValidNameValidator.kt, src/main/kotlin/com/sparta/tobiro/domain/member/validation/ValidPassword.kt, src/main/kotlin/com/sparta/tobiro/domain/member/validation/ValidPasswordValidator.kt, src/main/kotlin/com/sparta/tobiro/global/exception/GlobalExceptionHandler.kt
1. GlobalExceptionHandler 회원가입 name,password 유효성 검사 예외처리
2. @Valid를 Controller signUp 적용
3. @field: ValidName 를 Request에 적용
4. 유효성검사를 위한 ValidName 과 validPassword 작성
5. 예외처리를 위한 Validator 작성
=> ✨Feat: validation 구현

src/main/kotlin/com/sparta/tobiro/api/accommodation/controller/SearchController.kt, src/main/kotlin/com/sparta/tobiro/api/reservation/controller/ReservationController.kt, src/main/kotlin/com/sparta/tobiro/domain/accommodation/repository/AccommodationRepository.kt, src/main/kotlin/com/sparta/tobiro/domain/accommodation/repository/CustomRoomRepository.kt, src/main/kotlin/com/sparta/tobiro/domain/accommodation/repository/CustomRoomRepositoryImpl.kt, src/main/kotlin/com/sparta/tobiro/domain/accommodation/service/AccommodationService.kt, src/main/kotlin/com/sparta/tobiro/domain/reservation/model/Reservation.kt, src/main/kotlin/com/sparta/tobiro/domain/reservation/repository/CustomReservationRepository.kt, src/main/kotlin/com/sparta/tobiro/domain/reservation/repository/CustomReservationRepositoryImpl.kt, src/main/kotlin/com/sparta/tobiro/domain/reservation/service/ReservationService.kt, src/main/kotlin/com/sparta/tobiro/infra/security/SecurityConfig.kt
1. Controller, Service, Repo-querydsl 로직 작성
=> ✨Feat: 유저 서비스 - 객실 예약 내역 전체 조회

src/main/kotlin/com/sparta/tobiro/api/member/controller/MemberController.kt, src/main/kotlin/com/sparta/tobiro/api/member/controller/OwnerController.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/OwnerSignUpRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/UpdateMemberPasswordRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/UpdateOwnerPasswordRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Member.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/MemberRecentPasswords.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Owner.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/OwnerRecentPasswords.kt, src/main/kotlin/com/sparta/tobiro/domain/member/repository/MemberRecentPasswordsRepository.kt, src/main/kotlin/com/sparta/tobiro/domain/member/repository/OwnerRecentPasswordsRepository.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/MemberService.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/MemberServiceImpl.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/OwnerService.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/OwnerServiceImpl.kt, src/main/kotlin/com/sparta/tobiro/domain/member/validation/ValidBusinessNumber.kt, src/main/kotlin/com/sparta/tobiro/domain/member/validation/ValidBusinessValidator.kt, src/main/kotlin/com/sparta/tobiro/domain/member/validation/ValidNameValidator.kt, src/main/kotlin/com/sparta/tobiro/domain/member/validation/ValidPassword.kt
✨Feat:최근3번 사용한 password 사용제한
1. 새로운 Entity작성
2. Request 작성
3. Repository 작성
4. Controller 작성
5. service와 Impl 작성
=> ✨Feat:최근3번 사용한 password 사용제한

src/main/kotlin/com/sparta/tobiro/api/member/controller/MemberController.kt, src/main/kotlin/com/sparta/tobiro/api/member/controller/OwnerController.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/LoginRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/MemberSignUpRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/OwnerSignUpRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/UpdateMemberProfileRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/UpdateOwnerProfileRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/validation/ValidTlno.kt, src/main/kotlin/com/sparta/tobiro/domain/member/validation/ValidTlnoValidator.kt
✨Feat: ValidTlno추가 및 validation signUp과Login 프로필 추가
1. ValidTlno추가
2. signUp valideation 추가
3. Login valideation 추가
=> ✨Feat: ValidTlno추가 및 validation signUp과Login 프로필 추가

src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/MemberSignUpRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/OwnerSignUpRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/response/LoginResponse.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Member.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/MemberRecentPasswords.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Owner.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/OwnerRecentPasswords.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/MemberServiceImpl.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/OwnerServiceImpl.kt, src/main/kotlin/com/sparta/tobiro/domain/member/validation/ValidName.kt, src/main/kotlin/com/sparta/tobiro/domain/member/validation/ValidTlno.kt
1. Controller, Service, dto 수정
2. Entity 사진 url 컬럼 추가
3. request 사진 파일 받을 수 있도록 프로퍼티 추가
4. 이외 포맷팅 변경으로 인한 수정
=> 📝Fix: 로그인 API - 유저 정보 반환하도록 로직 수정

src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/MemberSignUpRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/OwnerSignUpRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/UpdateMemberProfileRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/UpdateOwnerProfileRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/model/Owner.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/OwnerServiceImpl.kt
1.name에 Validation 뺴기
2. SignUpRequest에 addcommodation tlno,name,address 추가해서 나누기
=> 📝Fix: SignUpRequest 수정 및 추가구현

src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/UpdateMemberProfileRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/dto/request/UpdateOwnerProfileRequest.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/MemberServiceImpl.kt, src/main/kotlin/com/sparta/tobiro/domain/member/service/OwnerServiceImpl.kt
Fix ProfileRequest에서 Email은 고유값이라 수정완료
=> ✨Fix ProfileRequest에서 Email은 고유값이라 수정완료

src/main/kotlin/com/sparta/tobiro/api/member/controller/MemberController.kt, src/main/kotlin/com/sparta/tobiro/api/member/controller/OwnerController.kt
Member,OwnerController에서 login로직에 @Valid 추가
=> ✨Feat: Member,Owner Controller에서 login로직에 @Valid 추가

src/main/kotlin/com/sparta/tobiro/domain/accommodation/repository/CustomRoomRepositoryImpl.kt
searchAccommodations 메소드 where 절 로직 and를 or로 변경
=> 🐛Bug: 숙박 가능한 방 조회시 예약 불가능한 방 제외 안되는 문제 해결
